spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha-usercenter?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    hikari:         #连接池
      username: root
      password: 795138462
      minimum-idle: 10          #最小空闲连接数
      maximum-pool-size: 20     #最大连接数
      max-lifetime: 180000      #空闲连接最长时间,超过该时间连接会被释放, 单位毫秒

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml