spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha-usercenter?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    hikari:                     #数据库连接池
      username: root
      password: 795138462
      minimum-idle: 10          #最小空闲连接数
      maximum-pool-size: 20     #最大连接数
      max-lifetime: 180000      #空闲连接最长时间,超过该时间连接会被释放, 单位毫秒
  redis:
    host: 127.0.0.1             #redis地址
    port: 6379                  #redis端口
    jedis:
      pool:
        max-active: 20          #redis连接池最大数
        min-idle: 10            #redis连接池最小线程数
    database: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   #注册中心 ip:port
  application:
    name: user-center                 #服务名
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #驼峰命名
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8081

#jwt秘钥
secret: aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrsssttt
#jwt过期时间
expire-time-in-second: 1209600